/*
 * Auto-generated by Frida. Please modify to match the signature of sub_15d4.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('sub_15d4()');
  },

  onLeave(log, retval, state) {
  }
});
